CREATE TABLE patients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(220),
    date_of_birth DATE
);
CREATE TABLE medical_histories (
    id SERIAL PRIMARY KEY,
    admitted_at TIMESTAMP,
   patient_id INT,
   status VARCHAR(220),
   CONSTRAINT fk_patient FOREIGN KEY(patient_id) REFERENCES patients(id)  
);
CREATE TABLE treatment (
    id SERIAL PRIMARY KEY,
    type VARCHAR(220),
    name VARCHAR(220)
);
CREATE TABLE medical_histories_treatments (
    medical_history_id int,
    treatment_id int,
    CONSTRAINT fk_medical_history FOREIGN KEY(medical_history_id) REFERENCES medical_histories(id),
    CONSTRAINT fk_treatment FOREIGN KEY(treatment_id) REFERENCES treatments(id)
);

CREATE TABLE invoices (
    id SERIAL PRIMARY KEY,
    total_amount DECIMAL,
    generated_at TIMESTAMP,
    payed_at TIMESTAMP,
    medical_history_id INT,
    CONSTRAINT fk_medical_history FOREIGN KEY(medical_history_id) REFERENCES medical_histories(id)
);

CREATE TABLE invoice_items(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_price DECIMAL(8, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    total_price DECIMAL(8, 2) NOT NULL,
    invoice_id INTEGER NOT NULL,
    treatment_id INTEGER NOT NULL
);

ALTER TABLE invoice_items
ADD CONSTRAINT invoice_items_invoice_id_foreign
FOREIGN KEY(invoice_id)
REFERENCES invoices(id);

ALTER TABLE invoice_items
ADD CONSTRAINT invoice_items_treatment_id_foreign
FOREIGN KEY(treatment_id)
REFERENCES treatments(id);

-- Foreign Key indexes
CREATE INDEX ON medical_histories (patient_id);

CREATE INDEX ON medical_histories_treatments (medical_history_id);
CREATE INDEX ON medical_histories_treatments (treatment_id);

CREATE INDEX ON invoices (medical_history_id);

CREATE INDEX ON invoice_items (invoice_id);
CREATE INDEX ON invoice_items (treatment_id);
